SYNTHETIC_JOBS = [
    {
        "title": "Backend Engineer",
        "company": "Sandbox Labs",
        "url": "https://synthetic-jobs.local/postings/backend-engineer",
        "description": "Build and maintain REST APIs in Python. Required: Python, FastAPI, PostgreSQL, Docker.",
        "location": "Remote",
        "source": "synthetic",
        "ats_type": "synthetic",
    },
    {
        "title": "Data Analyst",
        "company": "Sandbox Labs",
        "url": "https://synthetic-jobs.local/postings/data-analyst",
        "description": "Analyze product data and build dashboards. Required: SQL, Python, Tableau.",
        "location": "Remote",
        "source": "synthetic",
        "ats_type": "synthetic",
    },
    {
        "title": "Frontend Engineer",
        "company": "Sandbox Labs",
        "url": "https://synthetic-jobs.local/postings/frontend-engineer",
        "description": "Build UI in React and TypeScript. Required: React, TypeScript, CSS.",
        "location": "Remote",
        "source": "synthetic",
        "ats_type": "synthetic",
    },
    {
        "title": "Machine Learning Engineer",
        "company": "Sandbox Labs",
        "url": "https://synthetic-jobs.local/postings/ml-engineer",
        "description": "Train and deploy ML models. Required: Python, PyTorch, MLOps.",
        "location": "Remote",
        "source": "synthetic",
        "ats_type": "synthetic",
    },
    {
        "title": "DevOps Engineer",
        "company": "Sandbox Labs",
        "url": "https://synthetic-jobs.local/postings/devops-engineer",
        "description": "Manage CI/CD and cloud infrastructure. Required: AWS, Terraform, Docker, Kubernetes.",
        "location": "Remote",
        "source": "synthetic",
        "ats_type": "synthetic",
    },
    {
        "title": "Product Manager",
        "company": "Sandbox Labs",
        "url": "https://synthetic-jobs.local/postings/product-manager",
        "description": "Own product roadmap and work with engineering. Required: Product strategy, SQL, Agile.",
        "location": "Remote",
        "source": "synthetic",
        "ats_type": "synthetic",
    },
    {
        "title": "QA Engineer",
        "company": "Sandbox Labs",
        "url": "https://synthetic-jobs.local/postings/qa-engineer",
        "description": "Write automated test suites. Required: Python, Playwright, pytest.",
        "location": "Remote",
        "source": "synthetic",
        "ats_type": "synthetic",
    },
]
